### PR TITLE
feat: add api test

### PR DESCRIPTION
**Pull request by Fuochi**
Proposing a different test approach.
@davidnewhall since we are working with APIs, what do you think of mocking the server itself instead of the methods?

Proposing this for two main reasons:
- Testing the functions GetSomething by mocking the result of GetInto, doesn't test much
- This way you'll be able to catch errors from the APIer methods and check that the unmarshaling is working fine with the structs you define in the different clients.

On the other hand, tests will be longer to write and they won't use gomock.

Leaving this as draft since I wrote just one example to have some feedback

### CODE REVIEW

**Comment by davidnewhall** [comment]
I like this. I need to find more time to look at it more, but I haven't forgotten or decided this was bad or anything. Just been busy. Thank you for this!

**Comment by Fuochi** [comment]
Hi @davidnewhall,
have you thought about this?
I'd like to start writing tests when adding new methods

**Comment by davidnewhall** [comment]
Yeah, this is good. I'm okay with this. I would rather not keep mocks for the ever-changing APIer interface.

**Comment by Fuochi** [comment]
Great! I think I'll drop this PR and add tests following this approach whenever I either add new methods, or migrate the existing ones from returing ID to structs.

**Pull request closed without merging**
