### PR TITLE
Update system/status structs

### LINKED ISSUE #67: Update System/Status to pull all fields in api
- [x] [Radarr](https://github.com/Radarr/Radarr/blob/develop/src/Radarr.Api.V3/System/SystemController.cs)
- [x] [Sonarr](https://github.com/Sonarr/Sonarr/blob/develop/src/Sonarr.Api.V3/System/SystemController.cs)
- [x] [Lidarr](https://github.com/Lidarr/Lidarr/blob/develop/src/Lidarr.Api.V1/System/SystemController.cs)
- [x] [Readarr](https://github.com/Readarr/Readarr/blob/develop/src/Readarr.Api.V1/System/SystemController.cs)
- [x] [Prowlarr](https://github.com/Prowlarr/Prowlarr/blob/develop/src/Prowlarr.Api.V1/System/SystemController.cs)

### PR DESCRIPTION
**Pull request by davidnewhall**
Closes #67. 

Updates and alphabetizes structs for `system/status`.

### CODE REVIEW

**Review by Fuochi — APPROVED** [review]
just 2 notes:
1- please think about start writing tests, they'll save a lot of time
2- why alphabetic order for struct fields? lately, I've been thinking that we could try to lower the memory usage by sorting using `fieldalignment` or something similar. what do you think?

**Comment by davidnewhall** [comment]
Alphabetical seems like it makes it easy to identify changes.  But I also agree it's irrational given how Go stores structures in memory. 

I'll start putting tests in for any new methods.

**Comment by davidnewhall** [comment]
I played with this for a bit. Does not seem to matter what order I put the fields in, the Lidarr struct is always 328 bytes. Try it: https://go.dev/play/p/4zrxs5qm8Ir 

Maybe t's just that struct, but I'm not seeing an easy win here. :(

**Comment by Fuochi** [comment]
> I played with this for a bit. Does not seem to matter what order I put the fields in, the Lidarr struct is always 328 bytes. Try it: https://go.dev/play/p/4zrxs5qm8Ir
> 
> Maybe t's just that struct, but I'm not seeing an easy win here. :(

yes, since all fields but bool are multiple of 8 bytes, and there are 9 bool, the only way to have a bigger struct is to have 3 or more groups of bools (https://go.dev/play/p/d18Fu0jxx2d) I think that putting `time.Time` at first and `string` to follow should optimize a bit the runtime usage, but honestly, I didn't fully get how... more findings here: https://github.com/1pkg/gopium/issues/24#issuecomment-951203325

However, if there really is an improvement, we're talking about minimal. Hence, feel free do do as you prefer. 
The only real benefit that comes to my mind: If we use `fieldalignment -fix` and let it decide the order of the fields, we'll have consistency across the code, no matter who writes it.

**Comment by davidnewhall** [comment]
Can you link me to the `fieldalignment` tool you mentioned?

**Comment by Fuochi** [comment]
sure, package is: https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment
usage:
```sh
go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
fieldalignment -fix ./
```
it could be enabled as linter as well as part of `govet` in golangci:
```yaml
linters-settings:
  govet:
    enable:
      - fieldalignment
```

**Comment by Fuochi** [comment]
btw, it's really a small thing, don't waste too much time here

**Comment by davidnewhall** [comment]
```
lidarr/system.go:15:19: fieldalignment: struct with 320 pointer bytes could be 296 (govet)
type SystemStatus struct {
```

**Comment by davidnewhall** [comment]
I can only get this to work through golangci-lint, and not by running it directly I suspect I have a library out of date, but not sure how to fix it.

**Comment by davidnewhall** [comment]
I'm just going to worry about optimizing the structs later; there's hundreds that need fixing, and I can't get this dang tool to work right.

**Pull request merged**
